name: React Native CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # 推荐使用 LTS 版本
          cache: 'yarn'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev libxss1 \
            libasound2 libatk-bridge2.0-0 libgtk-3-0

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install project dependencies
        run: yarn install --frozen-lockfile

      - name: Run iOS build (simulator)
        run: yarn ios
        env:
          CI: true
          RCT_NO_LAUNCH_PACKAGER: true
