name: React Native CI (Yarn 4 - Fixed)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # 1. 强制清除全局 Yarn 1.x
      - name: Purge existing Yarn
        run: |
          npm uninstall -g yarn || true
          sudo rm -f $(which yarn) $(which yarnpkg)
          echo "Yarn removed: $(which yarn || echo 'Not found')"

      # 2. 设置 Node.js 20 (确保自带 Corepack)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      # 3. 强制激活项目指定的 Yarn 版本
      - name: Enforce Yarn 4.9.1
        run: |
          corepack enable
          corepack prepare yarn@4.9.1 --activate --yes
          yarn set version 4.9.1
          echo "Final Yarn version: $(yarn --version)"
          yarn config set nodeLinker node-modules  # 兼容传统工具链

  build-android:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 复用已配置的环境
      - name: Use pre-configured Yarn
        run: |
          echo "Using Yarn from Corepack: $(yarn --version)"
          yarn install --immutable --check-cache
          
      - name: Build Android
        run: yarn android
        env:
          CI: true

  build-ios:
    needs: setup
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use pre-configured Yarn
        run: |
          corepack enable
          yarn --version
          yarn install --immutable
          
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods -v 1.14.2
          cd ios && pod install --repo-update && cd ..
          
      - name: Build iOS
        run: yarn ios
        env:
          CI: true
