name: React Native CI (Yarn 4)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  # Android 构建 (Linux 环境)
  android-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 Node.js 20 (自带 Corepack)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn" # 自动缓存 Yarn Berry 的 .yarn/cache

      # 3. 启用 Corepack 并锁定 Yarn 4.9.1
      - name: Setup Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.9.1 --activate
          echo "Yarn version: $(yarn --version)"

      # 4. 安装系统依赖 (Android 构建所需)
      - name: Install Android dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libc6 libgcc1 libstdc++6 zlib1g

      # 5. 安装项目依赖 (严格模式)
      - name: Install project dependencies
        run: yarn install --immutable

      # 6. Android 构建
      - name: Build Android
        run: yarn android
        env:
          CI: true

  # iOS 构建 (macOS 环境)
  ios-build:
    needs: android-build # 可改为独立运行
    runs-on: macos-latest
    timeout-minutes: 40

    steps:
      # 1-3 步骤与 Android 相同
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
      - run: |
          corepack enable
          corepack prepare yarn@4.9.1 --activate
          yarn --version

      # 4. 安装 CocoaPods 依赖
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios && pod install --repo-update && cd ..

      # 5. iOS 构建
      - name: Build iOS
        run: yarn ios
        env:
          CI: true
          RCT_NO_LAUNCH_PACKAGER: true
