name: React Native CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Install Yarn (project-defined version)
        run: corepack prepare yarn@4.9.1 --activate

      - name: Install dependencies
        run: yarn install


      - name: Run iOS build (simulator)
        run: yarn ios
        env:
          CI: true
          RCT_NO_LAUNCH_PACKAGER: true
